# This file was generated by the {rix} R package v0.17.2 on 2025-11-15
# with following call:
# >rix(date = "2025-11-10",
#  > r_pkgs = c("languageserver",
#  > "rix",
#  > "here",
#  > "pacman",
#  > "data.table",
#  > "dplyr",
#  > "ggplot2",
#  > "fixest",
#  > "texreg",
#  > "kableExtra",
#  > "broom",
#  > "glue",
#  > "modelsummary"),
#  > system_pkgs = c("quarto",
#  > "git"),
#  > git_pkgs = NULL,
#  > jl_conf = list(jl_version = "1.11",
#  > jl_pkgs = c("DataFrames",
#  > "CSV",
#  > "LinearAlgebra",
#  > "Statistics")),
#  > ide = "none",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-10.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      broom
      data_table
      dplyr
      fixest
      ggplot2
      glue
      here
      kableExtra
      languageserver
      modelsummary
      pacman
      rix
      texreg;
  };
    
  jlconf = pkgs.julia_111.withPackages [ 
      "CSV"
      "DataFrames"
      "LinearAlgebra"
      "Statistics"
  ];
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      quarto
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs jlconf system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
